spring:
  datasource:
    url: jdbc:postgresql://db:5432/skyWingRacing
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  server:
    port: 8080
    servlet:
      context-path: /

  logging:
    level:
      org.springframework.web: DEBUG
      com.ys.skywingracing: DEBUG

  ##---------- API information ---------------------------------
  contact:
    email: youssefhihi18@gmail.com
  prod-server:
    url: http://localhost:8080
  project:
    version: 1.0
    title: Sky Wing Racing
    description: Sky Wing Racing
